#!/bin/bash

# Finding the root folder for this Ozma distribution
SOURCE=$0;
SCRIPT=`basename "$SOURCE"`;
while [ -h "$SOURCE" ]; do
    SCRIPT=`basename "$SOURCE"`;
    LOOKUP=`ls -ld "$SOURCE"`;
    TARGET=`expr "$LOOKUP" : '.*-> \(.*\)$'`;
    if expr "${TARGET:-.}/" : '/.*/$' > /dev/null; then
        SOURCE=${TARGET:-.};
    else
        SOURCE=`dirname "$SOURCE"`/${TARGET:-.};
    fi;
done;

# see #2092 from Scala
OZMA_HOME=`dirname "$SOURCE"`
OZMA_HOME=`cd "$OZMA_HOME"; pwd -P`

# Prepare
SRCDIR="$OZMA_HOME/src/runtime"
BUILDDIR="$OZMA_HOME/build/runtime"
OZMAC="$OZMA_HOME/bin/ozmac"

mkdir -p "$BUILDDIR/java/lang"
mkdir -p "$BUILDDIR/scala/ozma"
cd "$SRCDIR"

# Build Oz files
find . -name "*.oz" -exec ozc -c {} -o $BUILDDIR/{}f \;

# Build Ozma files
find . -name "*.scala" -print0 | xargs -0 "$OZMAC" -d "$BUILDDIR"
